default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
 
development:
  <<: *default
  database: bulletin_board
 
test:
  <<: *default
  database: bulletin_board
 
production:
  <<: *default
  database: bulletin_board
  username: root
  password: